### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by yahooo-m** [Tanveer81/RGNet#1]
Great work! 
When will you release the code?

**Comment by akshat-khare** [comment]
Same here. Waiting!!

**Comment by Tanveer81** [comment]
Hi,

Thanks for your interest in this work, RGNet.

The preprint manuscript is under review, and our current plan is to release the complete code once the manuscript is accepted.

I appreciate your patience.

**Comment by EricLina** [comment]
Hello?

**Comment by EricLina** [comment]
When will the code be released?

**Comment by Tanveer81** [comment]
Hi, thank you all for your patience. The code and weights are released.
