### ISSUE TITLE
Missing opt.json

### ISSUE THREAD

**Issue by Yiheng-Wang-TJ** [Tanveer81/RGNet#3]
Hi, I'm trying to apply RGNet to other benchmarks.
When I try to run inference.py, it reports the error:
FileNotFoundError: [Errno 2] No such file or directory: 'RGNet/opt.json'
Can you provide this json file? Thank you.

**Comment by Yiheng-Wang-TJ** [comment]
And without the opt.json, the configuration in rgnet/config.py seems to be incompatible with nlq checkpoint. When I try to load the checkpoint, some parameters are missing and some parameters don't have the correct shape.
Here's the error information:

Missing key(s) in state_dict: "transformer.decoder.layers.0.self_attn.in_proj_weight", "transformer.decoder.layers.0.self_attn.in_proj_bias", "transformer.decoder.layers.0.multihead_attn.in_proj_weight", "transformer.decoder.layers.0.multihead_attn.in_proj_bias", "transformer.decoder.layers.0.multihead_attn.out_proj.weight", "transformer.decoder.layers.0.multihead_attn.out_proj.bias", "transformer.decoder.layers.1.self_attn.in_proj_weight", "transformer.decoder.layers.1.self_attn.in_proj_bias", "transformer.decoder.layers.1.multihead_attn.in_proj_weight", "transformer.decoder.layers.1.multihead_attn.in_proj_bias", "transformer.decoder.layers.1.multihead_attn.out_proj.weight", "transformer.decoder.layers.1.multihead_attn.out_proj.bias", "transformer.decoder.layers.2.self_attn.in_proj_weight", "transformer.decoder.layers.2.self_attn.in_proj_bias", "transformer.decoder.layers.2.multihead_attn.in_proj_weight", "transformer.decoder.layers.2.multihead_attn.in_proj_bias", "transformer.decoder.layers.2.multihead_attn.out_proj.weight", "transformer.decoder.layers.2.multihead_attn.out_proj.bias", "transformer.decoder.layers.3.self_attn.in_proj_weight", "transformer.decoder.layers.3.self_attn.in_proj_bias", "transformer.decoder.layers.3.multihead_attn.in_proj_weight", "transformer.decoder.layers.3.multihead_attn.in_proj_bias", "transformer.decoder.layers.3.multihead_attn.out_proj.weight", "transformer.decoder.layers.3.multihead_attn.out_proj.bias", "transformer.decoder.layers.4.self_attn.in_proj_weight", "transformer.decoder.layers.4.self_attn.in_proj_bias", "transformer.decoder.layers.4.multihead_attn.in_proj_weight", "transformer.decoder.layers.4.multihead_attn.in_proj_bias", "transformer.decoder.layers.4.multihead_attn.out_proj.weight", "transformer.decoder.layers.4.multihead_attn.out_proj.bias", "transformer.decoder.layers.5.self_attn.in_proj_weight", "transformer.decoder.layers.5.self_attn.in_proj_bias", "transformer.decoder.layers.5.multihead_attn.in_proj_weight", "transformer.decoder.layers.5.multihead_attn.in_proj_bias", "transformer.decoder.layers.5.multihead_attn.out_proj.weight", "transformer.decoder.layers.5.multihead_attn.out_proj.bias". 
        Unexpected key(s) in state_dict: "global_rep_token", "global_rep_pos", "saliency_proj1.weight", "saliency_proj1.bias", "saliency_proj2.weight", "saliency_proj2.bias", "saliency_proj3.weight", "saliency_proj3.bias", "transformer.t2v_encoder.layers.0.self_attn.in_proj_weight", "transformer.t2v_encoder.layers.0.self_attn.in_proj_bias", "transformer.t2v_encoder.layers.0.self_attn.out_proj.weight", "transformer.t2v_encoder.layers.0.self_attn.out_proj.bias", "transformer.t2v_encoder.layers.0.linear1.weight", "transformer.t2v_encoder.layers.0.linear1.bias", "transformer.t2v_encoder.layers.0.linear2.weight", "transformer.t2v_encoder.layers.0.linear2.bias", "transformer.t2v_encoder.layers.0.norm1.weight", "transformer.t2v_encoder.layers.0.norm1.bias", "transformer.t2v_encoder.layers.0.norm2.weight", "transformer.t2v_encoder.layers.0.norm2.bias", "transformer.t2v_encoder.layers.1.self_attn.in_proj_weight", "transformer.t2v_encoder.layers.1.self_attn.in_proj_bias", "transformer.t2v_encoder.layers.1.self_attn.out_proj.weight", "transformer.t2v_encoder.layers.1.self_attn.out_proj.bias", "transformer.t2v_encoder.layers.1.linear1.weight", "transformer.t2v_encoder.layers.1.linear1.bias", "transformer.t2v_encoder.layers.1.linear2.weight", "transformer.t2v_encoder.layers.1.linear2.bias", "transformer.t2v_encoder.layers.1.norm1.weight", "transformer.t2v_encoder.layers.1.norm1.bias", "transformer.t2v_encoder.layers.1.norm2.weight", "transformer.t2v_encoder.layers.1.norm2.bias", "transformer.prop_instance.weight", "transformer.prop_instance.bias", "transformer.decoder.query_scale.layers.0.weight", "transformer.decoder.query_scale.layers.0.bias", "transformer.decoder.query_scale.layers.1.weight", "transformer.decoder.query_scale.layers.1.bias", "transformer.decoder.ref_point_head.layers.0.weight", "transformer.decoder.ref_point_head.layers.0.bias", "transformer.decoder.ref_point_head.layers.1.weight", "transformer.decoder.ref_point_head.layers.1.bias", "transformer.decoder.bbox_embed.0.layers.0.weight", "transformer.decoder.bbox_embed.0.layers.0.bias", "transformer.decoder.bbox_embed.0.layers.1.weight", "transformer.decoder.bbox_embed.0.layers.1.bias", "transformer.decoder.bbox_embed.0.layers.2.weight", "transformer.decoder.bbox_embed.0.layers.2.bias", "transformer.decoder.bbox_embed.1.layers.0.weight", "transformer.decoder.bbox_embed.1.layers.0.bias", "transformer.decoder.bbox_embed.1.layers.1.weight", "transformer.decoder.bbox_embed.1.layers.1.bias", "transformer.decoder.bbox_embed.1.layers.2.weight", "transformer.decoder.bbox_embed.1.layers.2.bias", "transformer.decoder.bbox_embed.2.layers.0.weight", "transformer.decoder.bbox_embed.2.layers.0.bias", "transformer.decoder.bbox_embed.2.layers.1.weight", "transformer.decoder.bbox_embed.2.layers.1.bias", "transformer.decoder.bbox_embed.2.layers.2.weight", "transformer.decoder.bbox_embed.2.layers.2.bias", "transformer.decoder.bbox_embed.3.layers.0.weight", "transformer.decoder.bbox_embed.3.layers.0.bias", "transformer.decoder.bbox_embed.3.layers.1.weight", "transformer.decoder.bbox_embed.3.layers.1.bias", "transformer.decoder.bbox_embed.3.layers.2.weight", "transformer.decoder.bbox_embed.3.layers.2.bias", "transformer.decoder.bbox_embed.4.layers.0.weight", "transformer.decoder.bbox_embed.4.layers.0.bias", "transformer.decoder.bbox_embed.4.layers.1.weight", "transformer.decoder.bbox_embed.4.layers.1.bias", "transformer.decoder.bbox_embed.4.layers.2.weight", "transformer.decoder.bbox_embed.4.layers.2.bias", "transformer.decoder.bbox_embed.5.layers.0.weight", "transformer.decoder.bbox_embed.5.layers.0.bias", "transformer.decoder.bbox_embed.5.layers.1.weight", "transformer.decoder.bbox_embed.5.layers.1.bias", "transformer.decoder.bbox_embed.5.layers.2.weight", "transformer.decoder.bbox_embed.5.layers.2.bias", "transformer.decoder.ref_anchor_head.layers.0.weight", "transformer.decoder.ref_anchor_head.layers.0.bias", "transformer.decoder.ref_anchor_head.layers.1.weight", "transformer.decoder.ref_anchor_head.layers.1.bias", "transformer.decoder.layers.0.sa_qcontent_proj.weight", "transformer.decoder.layers.0.sa_qcontent_proj.bias", "transformer.decoder.layers.0.sa_qpos_proj.weight", "transformer.decoder.layers.0.sa_qpos_proj.bias", "transformer.decoder.layers.0.sa_kcontent_proj.weight", "transformer.decoder.layers.0.sa_kcontent_proj.bias", "transformer.decoder.layers.0.sa_kpos_proj.weight", "transformer.decoder.layers.0.sa_kpos_proj.bias", "transformer.decoder.layers.0.sa_v_proj.weight", "transformer.decoder.layers.0.sa_v_proj.bias", "transformer.decoder.layers.0.ca_qcontent_proj.weight", "transformer.decoder.layers.0.ca_qcontent_proj.bias", "transformer.decoder.layers.0.ca_qpos_proj.weight", "transformer.decoder.layers.0.ca_qpos_proj.bias", "transformer.decoder.layers.0.ca_kcontent_proj.weight", "transformer.decoder.layers.0.ca_kcontent_proj.bias", "transformer.decoder.layers.0.ca_kpos_proj.weight", "transformer.decoder.layers.0.ca_kpos_proj.bias", "transformer.decoder.layers.0.ca_v_proj.weight", "transformer.decoder.layers.0.ca_v_proj.bias", "transformer.decoder.layers.0.ca_qpos_sine_proj.weight", "transformer.decoder.layers.0.ca_qpos_sine_proj.bias", "transformer.decoder.layers.0.cross_attn.out_proj.weight", "transformer.decoder.layers.0.cross_attn.out_proj.bias", "transformer.decoder.layers.1.sa_qcontent_proj.weight", "transformer.decoder.layers.1.sa_qcontent_proj.bias", "transformer.decoder.layers.1.sa_qpos_proj.weight", "transformer.decoder.layers.1.sa_qpos_proj.bias", "transformer.decoder.layers.1.sa_kcontent_proj.weight", "transformer.decoder.layers.1.sa_kcontent_proj.bias", "transformer.decoder.layers.1.sa_kpos_proj.weight", "transformer.decoder.layers.1.sa_kpos_proj.bias", "transformer.decoder.layers.1.sa_v_proj.weight", "transformer.decoder.layers.1.sa_v_proj.bias", "transformer.decoder.layers.1.ca_qcontent_proj.weight", "transformer.decoder.layers.1.ca_qcontent_proj.bias", "transformer.decoder.layers.1.ca_qpos_proj.weight", "transformer.decoder.layers.1.ca_qpos_proj.bias", "transformer.decoder.layers.1.ca_kcontent_proj.weight", "transformer.decoder.layers.1.ca_kcontent_proj.bias", "transformer.decoder.layers.1.ca_kpos_proj.weight", "transformer.decoder.layers.1.ca_kpos_proj.bias", "transformer.decoder.layers.1.ca_v_proj.weight", "transformer.decoder.layers.1.ca_v_proj.bias", "transformer.decoder.layers.1.ca_qpos_sine_proj.weight", "transformer.decoder.layers.1.ca_qpos_sine_proj.bias", "transformer.decoder.layers.1.cross_attn.out_proj.weight", "transformer.decoder.layers.1.cross_attn.out_proj.bias", "transformer.decoder.layers.2.sa_qcontent_proj.weight", "transformer.decoder.layers.2.sa_qcontent_proj.bias", "transformer.decoder.layers.2.sa_qpos_proj.weight", "transformer.decoder.layers.2.sa_qpos_proj.bias", "transformer.decoder.layers.2.sa_kcontent_proj.weight", "transformer.decoder.layers.2.sa_kcontent_proj.bias", "transformer.decoder.layers.2.sa_kpos_proj.weight", "transformer.decoder.layers.2.sa_kpos_proj.bias", "transformer.decoder.layers.2.sa_v_proj.weight", "transformer.decoder.layers.2.sa_v_proj.bias", "transformer.decoder.layers.2.ca_qcontent_proj.weight", "transformer.decoder.layers.2.ca_qcontent_proj.bias", "transformer.decoder.layers.2.ca_qpos_proj.weight", "transformer.decoder.layers.2.ca_qpos_proj.bias", "transformer.decoder.layers.2.ca_kcontent_proj.weight", "transformer.decoder.layers.2.ca_kcontent_proj.bias", "transformer.decoder.layers.2.ca_kpos_proj.weight", "transformer.decoder.layers.2.ca_kpos_proj.bias", "transformer.decoder.layers.2.ca_v_proj.weight", "transformer.decoder.layers.2.ca_v_proj.bias", "transformer.decoder.layers.2.ca_qpos_sine_proj.weight", "transformer.decoder.layers.2.ca_qpos_sine_proj.bias", "transformer.decoder.layers.2.cross_attn.out_proj.weight", "transformer.decoder.layers.2.cross_attn.out_proj.bias", "transformer.decoder.layers.3.sa_qcontent_proj.weight", "transformer.decoder.layers.3.sa_qcontent_proj.bias", "transformer.decoder.layers.3.sa_qpos_proj.weight", "transformer.decoder.layers.3.sa_qpos_proj.bias", "transformer.decoder.layers.3.sa_kcontent_proj.weight", "transformer.decoder.layers.3.sa_kcontent_proj.bias", "transformer.decoder.layers.3.sa_kpos_proj.weight", "transformer.decoder.layers.3.sa_kpos_proj.bias", "transformer.decoder.layers.3.sa_v_proj.weight", "transformer.decoder.layers.3.sa_v_proj.bias", "transformer.decoder.layers.3.ca_qcontent_proj.weight", "transformer.decoder.layers.3.ca_qcontent_proj.bias", "transformer.decoder.layers.3.ca_qpos_proj.weight", "transformer.decoder.layers.3.ca_qpos_proj.bias", "transformer.decoder.layers.3.ca_kcontent_proj.weight", "transformer.decoder.layers.3.ca_kcontent_proj.bias", "transformer.decoder.layers.3.ca_kpos_proj.weight", "transformer.decoder.layers.3.ca_kpos_proj.bias", "transformer.decoder.layers.3.ca_v_proj.weight", "transformer.decoder.layers.3.ca_v_proj.bias", "transformer.decoder.layers.3.ca_qpos_sine_proj.weight", "transformer.decoder.layers.3.ca_qpos_sine_proj.bias", "transformer.decoder.layers.3.cross_attn.out_proj.weight", "transformer.decoder.layers.3.cross_attn.out_proj.bias", "transformer.decoder.layers.4.sa_qcontent_proj.weight", "transformer.decoder.layers.4.sa_qcontent_proj.bias", "transformer.decoder.layers.4.sa_qpos_proj.weight", "transformer.decoder.layers.4.sa_qpos_proj.bias", "transformer.decoder.layers.4.sa_kcontent_proj.weight", "transformer.decoder.layers.4.sa_kcontent_proj.bias", "transformer.decoder.layers.4.sa_kpos_proj.weight", "transformer.decoder.layers.4.sa_kpos_proj.bias", "transformer.decoder.layers.4.sa_v_proj.weight", "transformer.decoder.layers.4.sa_v_proj.bias", "transformer.decoder.layers.4.ca_qcontent_proj.weight", "transformer.decoder.layers.4.ca_qcontent_proj.bias", "transformer.decoder.layers.4.ca_qpos_proj.weight", "transformer.decoder.layers.4.ca_qpos_proj.bias", "transformer.decoder.layers.4.ca_kcontent_proj.weight", "transformer.decoder.layers.4.ca_kcontent_proj.bias", "transformer.decoder.layers.4.ca_kpos_proj.weight", "transformer.decoder.layers.4.ca_kpos_proj.bias", "transformer.decoder.layers.4.ca_v_proj.weight", "transformer.decoder.layers.4.ca_v_proj.bias", "transformer.decoder.layers.4.ca_qpos_sine_proj.weight", "transformer.decoder.layers.4.ca_qpos_sine_proj.bias", "transformer.decoder.layers.4.cross_attn.out_proj.weight", "transformer.decoder.layers.4.cross_attn.out_proj.bias", "transformer.decoder.layers.5.sa_qcontent_proj.weight", "transformer.decoder.layers.5.sa_qcontent_proj.bias", "transformer.decoder.layers.5.sa_qpos_proj.weight", "transformer.decoder.layers.5.sa_qpos_proj.bias", "transformer.decoder.layers.5.sa_kcontent_proj.weight", "transformer.decoder.layers.5.sa_kcontent_proj.bias", "transformer.decoder.layers.5.sa_kpos_proj.weight", "transformer.decoder.layers.5.sa_kpos_proj.bias", "transformer.decoder.layers.5.sa_v_proj.weight", "transformer.decoder.layers.5.sa_v_proj.bias", "transformer.decoder.layers.5.ca_qcontent_proj.weight", "transformer.decoder.layers.5.ca_qcontent_proj.bias", "transformer.decoder.layers.5.ca_qpos_proj.weight", "transformer.decoder.layers.5.ca_qpos_proj.bias", "transformer.decoder.layers.5.ca_kcontent_proj.weight", "transformer.decoder.layers.5.ca_kcontent_proj.bias", "transformer.decoder.layers.5.ca_kpos_proj.weight", "transformer.decoder.layers.5.ca_kpos_proj.bias", "transformer.decoder.layers.5.ca_v_proj.weight", "transformer.decoder.layers.5.ca_v_proj.bias", "transformer.decoder.layers.5.ca_qpos_sine_proj.weight", "transformer.decoder.layers.5.ca_qpos_sine_proj.bias", "transformer.decoder.layers.5.cross_attn.out_proj.weight", "transformer.decoder.layers.5.cross_attn.out_proj.bias". 
        size mismatch for query_embed.weight: copying a param with shape torch.Size([5, 2]) from checkpoint, the shape in current model is torch.Size([5, 256]).

**Comment by Tanveer81** [comment]
Hi, thanks you for finding the problem. I have added all the opt.json files in the [weight folder ](https://drive.google.com/drive/folders/1y5QSCLQKpKy2cBuflefWvOhrb5ysDLry). You would have to change the PATH variable. Can you let me know if this works?

**Comment by Yiheng-Wang-TJ** [comment]
Yes, it works.Thank you!
